### ISSUE TITLE
Button click property inside Cube.pde

### ISSUE THREAD

**Issue by Logenleedev** [MacTuitui/toio_processing#1]
I noticed that toio contains a button inside. When we press it, there is a click sound. I was just wondering, is there a boolean property that records whether the button is pressed or not?

**Comment by MacTuitui** [comment]
I have not tracked the state of the button per cube, but you should be getting the events here https://github.com/MacTuitui/toio_processing/blob/main/toio_processing.pde#L285

If you follow what I did for tracking the position you should be able to keep the state of the button per cube.

**Comment by Logenleedev** [comment]
Wow. Really fast reply! Now it works! Thanks!
